### ISSUE TITLE
Track down the out-of-bounds bug

### ISSUE THREAD

**Issue by hepplerj** [hepplerj/midwest-map-population#2]
There's a problem, either with `draw_demographics()` or `filter_by_demographics` that is causing the Leaflet map to fail.

**Comment by hepplerj** [comment]
Error log:

```
> runApp()

Listening on http://127.0.0.1:5367
Parsed with column specification:
cols(
  id = col_integer(),
  st = col_character(),
  city = col_character(),
  cityst = col_character(),
  county_name = col_character(),
  year = col_integer(),
  population = col_integer(),
  lat = col_double(),
  lng = col_double()
)
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
Warning: Error in pal: object 'input' not found
Stack trace (innermost first):
    102: pal
    101: eval
    100: eval
     99: resolveFormula
     98: FUN
     97: lapply
     96: FUN
     95: lapply
     94: evalAll
     93: evalFormula
     92: invokeMethod
     91: eval
     90: eval
     89: %>%
     88: addPolygons
     87: function_list[[k]]
     86: withVisible
     85: freduce
     84: _fseq
     83: eval
     82: eval
     81: withVisible
     80: %>%
     79: draw_demographics [helpers.R#60]
     78: func [/Users/jheppler/Dropbox/github/midwest-map-population/server.R#61]
     77: origRenderFunc
     76: output$cities_map
      1: runApp
Warning: Error in [[: subscript out of bounds
Stack trace (innermost first):
    87: <reactive:demographics_filtered> [/Users/jheppler/Dropbox/github/midwest-map-population/server.R#29]
    76: demographics_filtered
    75: derivePolygons
    74: addPolygons
    73: function_list[[k]]
    72: withVisible
    71: freduce
    70: _fseq
    69: eval
    68: eval
    67: withVisible
    66: %>%
    65: draw_demographics [helpers.R#60]
    64: function_list[[k]]
    63: withVisible
    62: freduce
    61: _fseq
    60: eval
    59: eval
    58: withVisible
    57: %>%
    56: observerFunc [/Users/jheppler/Dropbox/github/midwest-map-population/server.R#91]
     1: runApp
```

**Comment by lmullen** [comment]
I can't test the error because I can't read in the counties data, which are not in the repository. 

But from your stack trace, I'd guess the problem might be somewhere around here: https://github.com/hepplerj/midwest-map-population/blob/master/helpers.R#L58

I'm not sure why the `pal()` function is being created with `NULL` as its domain. But somewhere around there it is unable to find `input`. I'm not sure what's going on with the scoping, but you're trying to use the special Shiny `input` variable, and it's not being found in that helper function, I'd guess. I'd start by putting a `print()` call in that helper function so you can figure out what `input` is at that point. Or you could pass `input` into the helper function so that is a pure function and not relying on a variable outside the scope of the function.

**Comment by hepplerj** [comment]
I've used `NULL` so the domain is inferred by the data each time, though there's probably no reason I couldn't set a consistent quantile range for the data. And now that I think of it, it's probably bad visualization practice. 

I'll attempt passing `input` as a pure function and see what happens.

**Comment by hepplerj** [comment]
@lmullen If you're keen to try it out, I have the shapefiles in the repository now. I fixed a few bugs, but I'm running into one more yet. It doesn't appear that my default `selectInput` of `totalPop` is being passed to the `draw_demographic()` function. Would that need its own `reactive` to handle that?

**Comment by hepplerj** [comment]
Issue fixed, related in part to `input$year` not being passed as a character.
